name = "StokesFlowInRigidTube"
uuid = "b67001c1-12f6-4844-89ab-a2ec1e37179b"
authors = ["Ali Gurbuz <aligurbu@buffalo.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
